name: Auto-Pack

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v1
      - name: Download Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Dependces
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
      - name: Add version to the python file
        shell: python
        run: |
          version =  """${{ steps.commit.outputs.short }}"""
          with open('main.py','r',encoding='utf8') as origin_file:
            origin = origin_file.read()
          new="print('幸运大抽奖 "+version+".beta')\n"+origin
          with open('main.py','w',encoding='utf8') as new_file:
            new_file.write(new)

      - name: Pack to exe
        run: |
          mkdir ${{ steps.commit.outputs.short }}
          pyinstaller -F main.py
          mv dist/*.exe ${{ steps.commit.outputs.short }}/
          mv README.md ${{ steps.commit.outputs.short }}/
          mv LICENSE ${{ steps.commit.outputs.short }}/
          mv n2n.json ${{ steps.commit.outputs.short }}/
          Compress-Archive -Path ${{ steps.commit.outputs.short }} -DestinationPath ${{ steps.commit.outputs.short }}.zip
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.commit.outputs.short }}
          path: ${{ steps.commit.outputs.short }}
      - name: Create Pre-release And Upload Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.commit.outputs.short }}.zip
          file_glob: true
          tag: ${{ steps.commit.outputs.short }}
          overwrite: true
          release_name: ${{ steps.commit.outputs.short }}
          body: |
            此为自动打包版本，可能存在不稳定性
            版本号为commit前七位
          prerelease: true
