name: Pack_And_Release

on:
  workflow_dispatch:
    inputs:
      Release_Version:
        description: '发布版本'
        required: true
        default: 'v1.0'
      Release_Describe:
        description: '版本说明'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Dependces
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyinstaller
      - name: Add version to the python file
        shell: python
        run: |
          version =  """${{ github.event.inputs.Release_Version }}"""
          with open('main.py','r',encoding='utf8') as origin_file:
            origin = origin_file.read()
          new="print('幸运大抽奖 v"+version+"')\n"+origin
          with open('main.py','w',encoding='utf8') as new_file:
            new_file.write(new)

      - name: Pack to exe
        run: |
          mkdir ${{ github.event.inputs.Release_Version }}
          pyinstaller -F main.py
          mv dist/*.exe ${{ github.event.inputs.Release_Version }}/
          mv README.md ${{ github.event.inputs.Release_Version }}/
          mv LICENSE ${{ github.event.inputs.Release_Version }}/
          mv n2n.json ${{ github.event.inputs.Release_Version }}/
          Compress-Archive -Path ${{ github.event.inputs.Release_Version }} -DestinationPath ${{ github.event.inputs.Release_Version }}.zip
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.inputs.Release_Version }}
          path: ${{ github.event.inputs.Release_Version }}
      - name: create release and upload asset
        if: ${{ github.event.inputs.Release_Version != 'none' && github.event.inputs.Release_Version != '' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.event.inputs.Release_Version }}.zip
          file_glob: true
          tag: ${{ github.event.inputs.Release_Version }}
          overwrite: true
          release_name: "${{ github.event.inputs.Release_Version }}"
          body: "${{ github.event.inputs.Release_Describe }}"
     
